using MongoDB.Bson.Serialization.Attributes;

namespace eCommerce.OrdersMicroservice.DataAccessLayer.Entities;

public class Order
{
    [BsonId]
    [BsonRepresentation(MongoDB.Bson.BsonType.String)]
    public Guid _id { get; set; } // every doc must have _id column, seperate unique - automatically generated by mongodb
    //can add [BsonId] to OrderId if we dont want _id to eb egenetarted
    //by mongodb driver requires _id and only it can be used as id using [BsonId] , so must add it
    //must have _id as mapping property

    [BsonRepresentation(MongoDB.Bson.BsonType.String)]
    public Guid OrderID { get; set; } // stored as UUID binary data by default - want tos tore it as plain string 
    //to force it we can add Binary json bson represrbtaion

    [BsonRepresentation(MongoDB.Bson.BsonType.String)]
    public Guid UserID { get; set; }

    [BsonRepresentation(MongoDB.Bson.BsonType.String)]
    public DateTime OrderDate { get; set; }

    [BsonRepresentation(MongoDB.Bson.BsonType.Double)] // double is 8 bytes
    public decimal TotalBill { get; set; }

    public List<OrderItem> OrderItems { get; set; } = new List<OrderItem>();
}